// node tools/build.mjs
//   → dist/whereabouts.html  the single file to publish as the Claude artifact
//   → docs/index.html        the same page for GitHub Pages, plus what a phone needs to
//                            install it to the home screen and open it full screen
//                            (icons come from tools/make-icons.mjs)
import fs from 'node:fs';
import crypto from 'node:crypto';
import path from 'node:path';
import { ROOT, page } from './assemble.mjs';

const html = page();
const write = (rel, text) => {
  const out = path.join(ROOT, rel);
  fs.mkdirSync(path.dirname(out), { recursive: true });
  fs.writeFileSync(out, text);
  console.log(`built ${rel} (${(Buffer.byteLength(text) / 1024).toFixed(1)} KB)`);
};

write('dist/whereabouts.html', html);

const INSTALL = `<link rel="manifest" href="manifest.webmanifest">
<link rel="apple-touch-icon" href="icon-180.png">
<link rel="icon" type="image/png" href="icon-192.png">
<meta name="theme-color" content="#FFD7A8">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="apple-mobile-web-app-title" content="Whereabouts">
`;
if (!html.includes('</title>\n')) throw new Error('no </title> to put the install tags after');
write('docs/index.html', html.replace('</title>\n', () => '</title>\n' + INSTALL));
write('docs/manifest.webmanifest', JSON.stringify({
  name: 'Whereabouts',
  short_name: 'Whereabouts',
  description: 'A co-op I spy game in a tiny 3D island town.',
  start_url: './',
  scope: './',
  display: 'fullscreen',
  orientation: 'landscape',
  background_color: '#FFD7A8',
  theme_color: '#FFD7A8',
  icons: [
    { src: 'icon-192.png', sizes: '192x192', type: 'image/png' },
    { src: 'icon-512.png', sizes: '512x512', type: 'image/png', purpose: 'any maskable' },
  ],
}, null, 2) + '\n');
// offline play: a service worker that keeps the game and its libraries on the phone
const version = crypto.createHash('sha1').update(html).digest('hex').slice(0, 10);
write('docs/sw.js', `// Whereabouts offline cache (generated by tools/build.mjs)
const CACHE = 'wb-${version}';
const CORE = ['./', './index.html', './manifest.webmanifest', './icon-180.png', './icon-192.png', './icon-512.png',
  'https://cdn.jsdelivr.net/npm/three@0.149.0/build/three.min.js', 'https://cdn.jsdelivr.net/npm/mqtt@5.16.0/dist/mqtt.min.js'];
self.addEventListener('install', e => e.waitUntil(caches.open(CACHE)
  .then(c => Promise.all(CORE.map(u => c.add(u).catch(() => {})))).then(() => self.skipWaiting())));
self.addEventListener('activate', e => e.waitUntil(caches.keys()
  .then(keys => Promise.all(keys.filter(k => k.startsWith('wb-') && k !== CACHE).map(k => caches.delete(k))))
  .then(() => self.clients.claim())));
const keep = u => u.origin === location.origin || ['cdn.jsdelivr.net', 'fonts.googleapis.com', 'fonts.gstatic.com'].includes(u.hostname);
self.addEventListener('fetch', e => {
  const req = e.request, url = new URL(req.url);
  if (req.method !== 'GET' || !keep(url)) return;
  // the page itself: newest when online, the saved copy when not
  if (req.mode === 'navigate') {
    e.respondWith(fetch(req).then(r => { const copy = r.clone(); caches.open(CACHE).then(c => c.put('./index.html', copy)); return r; })
      .catch(() => caches.match('./index.html')));
    return;
  }
  // everything else: the saved copy first, fetched and saved when missing
  e.respondWith(caches.match(req).then(hit => hit || fetch(req).then(r => {
    if (r.ok || r.type === 'opaque') { const copy = r.clone(); caches.open(CACHE).then(c => c.put(req, copy)); }
    return r;
  })));
});
`);
// plain files only: tell GitHub Pages not to run them through Jekyll
fs.writeFileSync(path.join(ROOT, 'docs', '.nojekyll'), '');
